# Hao.jiangyu.org Configuration

favicon: https://cdn.jiangyu.org/logo-jiangyu.png
banner: 

logo:
  expanded: /images/logo.png
  collapsed: /images/logo-jiangyu.png
  dark: /images/logo-jiangyu.png

flag:
  icon: flag-cn
  name: 中文


menu:
  - name: 常用工具
    icon: far fa-star
    submenu:
      - name: 常用工具
        icon: fas fa-wrench
        config: my
      - name: 安防工具
        icon: fas fa-video
        config: videotool
  - name: 常用软件
    icon: fas fa-cube
    config: software
  - name: 安防行业
    icon: fas fa-shield-alt
    submenu:
      - name: 视频监控
        icon: fas fa-video
        config: video
      - name: 图像传感器
        icon: fas fa-photo-video
        config: sensor
      - name: 处理器DSP
        icon: fas fa-microchip
        config: dsp
      - name: 模组方案商
        icon: fas fa-cube
        config: module
      - name: P2P平台
        icon: fas fa-cloud
        config: P2P
      - name: 系统平台
        icon: fas fa-server
        config: vms
      - name: 系统集成商
        icon: fas fa-square-full
        config: supply
      - name: AI智能算法
        icon: fas fa-dna
        config: AI
      - name: 消费类摄像机
        icon: fas fa-wifi
        config: wifi
      - name: 行业网站
        icon: fas fa-sitemap
        config: sitemap
      - name: 热成像仪
        icon: fas fa-thermometer-full
        config: ir
      - name: 存储
        icon: fas fa-hdd
        config: hdd
      - name: 镜头
        icon: fas fa-circle
        config: lens

video:
  - name: 海康威视
    url: https://www.hikvision.com
    img: https://www.hikvision.com/etc/clientlibs/it/resources/icons/color-logo.svg
    description: 全球最大的视频安防产品提供商。
  - name: 大华
    url: https://www.dahuatech.com/
    img: https://www.dahuatech.com/bocweb/web/img/logo.png
    description: 中国第二大安防视频监控产品提供商。
  - name: 宇视
    url: https://cn.uniview.com/
    img: https://cn.uniview.com/tres/images/Yushi_Site/blue/logo.png
    description: 中国第三大安防视频监控产品提供商。
  - name: 宇视
    url: https://www.axis.com/zh-cn
    img: https://www.axis.com/sites/all/themes/axis_bootstrap_subtheme/images/axis_logo.png
    description: 全球第三大安防视频监控产品提供商。


sensor:
  - name: SONY
    url: https://www.sony-semicon.co.jp/e/
    img: https://www.sony-semicon.co.jp/common/images/sony.gif
    description: SONY图像传感器。
  - name: OmniVision
    url: https://www.ovt.com/
    img: https://www.ovt.com/download/sites/14/share.jpg
    description: 中资收购的美国图像传感器品牌。
  - name: 思特威(smartsens)
    url: http://www.smartsenstech.com/
    img: http://www.smartsenstech.com/templates/sitewei/favicon.ico
    description: 中国新兴的从事CMOS图像传感器芯片产品研发、设计及服务的企业。


dsp:
  - name: 华为海思
    url: http://www.hisilicon.com/
    img: http://www.hisilicon.com/Assets/Hisilicon/img/favicon.ico
    description: 华为海思。
  - name: 安霸
    url: https://www.ambarella.com.cn/
    img: https://www.ambarella.com.cn/wp-content/themes/ambarella/img/favicons/favicon.ico
    description: 安霸Ambarella。
  - name: Ingenic-北京君正
    url: http://www.ingenic.com.cn/
    img: http://www.ingenic.com.cn/image/logo.jpg
    description: 北京君正集成电路股份有限公司。
  - name: 国科
    url: http://www.gokemicro.com/
    img: http://www.gokemicro.com/favicon.ico
    description: 国科微电子股份有限公司。
  - name: 富瀚
    url: https://www.fullhan.com/
    img: https://www.fullhan.com/theme/fuhan/images/logo.png
    description: 上海富瀚微电子股份有限公司。
  - name: Nextchip
    url: http://nextchip.com/
    img: http://www.nextchip.com/ch/images/favi_icon.ico
    description: Nextchip.
  - name: Techpoint
    url: http://techpointinc.net/
    img: http://techpointinc.net/images/logo.jpg
    description: Techpoint.
  - name: XM
    url: http://www.xiongmaitech.com/
    img: http://www.xiongmaitech.com/favicon.ico
    description: 雄迈集成电路有限公司。

module:
  - name: 海康威视
    url: https://www.hikvision.com
    img: https://www.hikvision.com/etc/clientlibs/it/resources/icons/color-logo.svg
    description: 全球最大的视频安防产品提供商。

P2P:
  - name: 海康威视
    url: https://www.hikvision.com
    img: https://www.hikvision.com/etc/clientlibs/it/resources/icons/color-logo.svg
    description: 全球最大的视频安防产品提供商。

vms:
  - name: 海康威视
    url: https://www.hikvision.com
    img: https://www.hikvision.com/etc/clientlibs/it/resources/icons/color-logo.svg
    description: 全球最大的视频安防产品提供商。
    
supply:
  - name: 海康威视
    url: https://www.hikvision.com
    img: https://www.hikvision.com/etc/clientlibs/it/resources/icons/color-logo.svg
    description: 全球最大的视频安防产品提供商。    
    
AI:
  - name: 海康威视
    url: https://www.hikvision.com
    img: https://www.hikvision.com/etc/clientlibs/it/resources/icons/color-logo.svg
    description: 全球最大的视频安防产品提供商。  
 
wifi:
  - name: 海康威视
    url: https://www.hikvision.com
    img: https://www.hikvision.com/etc/clientlibs/it/resources/icons/color-logo.svg
    description: 全球最大的视频安防产品提供商。
 
sitemap:
  - name: A&S台湾版
    url: https://www.asmag.com.tw/
    img: https://www.asmag.com/images/asmag.ico
    description: A&S安防知识网台湾版。
  - name: Information Security 資安人科技網
    url: https://www.informationsecurity.com.tw/
    img: https://www.informationsecurity.com.tw/images/info.ico
    description: 台湾安防资讯网站。
ir:
  - name: 海康威视
    url: https://www.hikvision.com
    img: https://www.hikvision.com/etc/clientlibs/it/resources/icons/color-logo.svg
    description: 全球最大的视频安防产品提供商。 
  - name: 海康威视
    url: https://www.hikvision.com
    img: https://www.hikvision.com/etc/clientlibs/it/resources/icons/color-logo.svg
    description: 全球最大的视频安防产品提供商。 
lens:
  - name: 海康威视
    url: https://www.hikvision.com
    img: https://www.hikvision.com/etc/clientlibs/it/resources/icons/color-logo.svg
    description: 全球最大的视频安防产品提供商。
hdd:
  - name: 海康威视
    url: https://www.hikvision.com
    img: https://www.hikvision.com/etc/clientlibs/it/resources/icons/color-logo.svg
    description: 全球最大的视频安防产品提供商。
my:
  - name: Wetransfer
    url: https://wetransfer.com/
    img: https://prod-cdn.wetransfer.net/packs/media/images/wt-facebook-9db47080.png
    description: 短期文件存储分享网站。
  - name: 奶牛快传
    url: https://www.c-t.work/
    img: https://background.cowtransfer.com/apple-icon-114x114.png
    description: 国内山寨wetransfer的网站。
  - name: 在线PS
    url: https://ps.gaoding.com/
    img: https://ps.gaoding.com/favicon.ico
    description: 在外面偶尔需要PS，但是电脑没装软件，可以使用网页版的在线PS。
  - name: 百度脑图
    url: https://naotu.baidu.com/
    img: https://naotu.baidu.com/favicon.ico
    description: 百度脑图，便捷的脑图编辑工具- 免安装 云存储。
  - name: smallpdf
    url: https://smallpdf.com/cn
    img: https://smallpdf.com/favicon.png
    description: 功能一应俱全、简单好用的线上 PDF 工具。

videotool:
  - name: 海康安防计算器
    url: https://h5proxy.hikvision.com/jf/videocal/index.html#/
    img: 
    description: 海康安防计算器。
  - name: 大华安防计算器
    url: https://www.dahuatech.com/support/work/#/home
    img: 
    description: 大华安防计算器。
  - name: Axis镜头选型计算
    url: https://www.axis.com/en-us/tools/lens-calculator
    img: https://www.axis.com/sites/all/themes/axis_bootstrap_subtheme/favicon.ico
    description: Axis镜头选型计算工具。
  - name: Axis工具
    url: https://www.axis.com/en-us/tools
    img: https://www.axis.com/sites/all/themes/axis_bootstrap_subtheme/favicon.ico
    description: Axis工具
    
software:
  - name: itellyou
    url: https://next.itellyou.cn/
    img: https://next.itellyou.cn/favicon.ico
    description: 提供可靠的Microsoft原版软件。
about:
  url: https://www.jiangyu.org
  icon: far fa-heart
  name: 关于本站


since: 2020

js:
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /js/bootstrap.min.js
  TweenMax: /js/TweenMax.min.js
  resizeable: /js/resizeable.min.js
  joinable: /js/joinable.js
  xenonApi: /js/xenon-api.min.js
  xenonToggles: /js/xenon-toggles.min.js
  xenonCustom: /js/xenon-custom.min.js
  lozad: /js/lozad.min.js
  html5shiv: /js/html5shiv.min.js
  respond: /js/respond.min.js

css:
  fonts: //fonts.loli.net/css?family=Noto+Sans+SC:400,700,400italic.css
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css

